### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by jccastromil** [BBVA/apicheck#22]
Hi guys,

I am trying to follow the installation instructions and when I type this command an error message is returned:

docker run --rm bbvalabs/apicheck -h

Unable to find image 'bbvalabs/apicheck:latest' locally
docker: Error response from daemon: pull access denied for bbvalabs/apicheck, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

Any idea?

Thx

**Comment by panchoh** [comment]
Hi, @jccastromil.

Sorry for the not up-to-date doc.  `apicheck` is under heavy development, and some things have changed quite a bit.

In its current form, `apicheck` is composed as a *toolset*, where each tool is to be containerized into its own `Docker` image.

Each of these tools live under the `tools` directory.

Each has its own directory, e.g.: `send-to-proxy`.

Within each tool directory, there is a `META` file.

In this file a `name` is defined.  That is the name of the `Docker` image that contains the app, which gets published automatically on `Docker Hub`, under the `bbvalabs` namespace.

Hope that it helps!

Thanks for your patience and interest.

**Comment by panchoh** [comment]
Closing now.
