### ISSUE TITLE
Proposal: alternative OAS tool with extensible rules

### ISSUE THREAD

**Issue by ioggstream** [BBVA/apicheck#30]
## Proposal

I'm willing to provide another OAS3 linting tool based on Spectral. I'm working on a set of security rules which are not provided by speccy, to ensure:

- numbers, strings and arrays are properly constrained;
- endpoints use https://
- Cache policy prevent euristic caching
- PATCH content-type avoids bad behavior

## Notes

- I chose Spectral because it supports both javascript and yaml rules;
- rule sources are [here](https://github.com/teamdigitale/api-oas-checker/tree/master/rules)
   but you can just use the [assembled spectral.yml](https://teamdigitale.github.io/api-oas-checker/spectral.yml)
- the initial work on security rules is [here](https://github.com/teamdigitale/api-oas-checker/pull/58) and it will be delivered in another file (eg. spectral-security.yml)

Your feedback is welcome!

**Comment by cr0hn** [comment]
It sound very good! Maybe would be possible to integrate it and send us a PR?

Integrating a new tools is really easy:

https://bbva.github.io/apicheck/docs/integrating-new-tools

**Comment by ioggstream** [comment]
@cr0hn I'll asap it :)

**Comment by cr0hn** [comment]
WoW nice!
