### ISSUE TITLE
OAS check inconsistent name and URL

### ISSUE THREAD

**Issue by mbarnach** [BBVA/apicheck#33]
When issuing `use-problem-json-for-errors`, the message shows an inconsistency between the URL and the name:
Name: RFC 7807
URL: https://tools.ietf.org/html/rfc6648

**Comment by ioggstream** [comment]
Hi @mbarnach thanks for filing this!

It is now fixed in both master and https://github.com/BBVA/apicheck/pull/39 - I just update security rules.

Can we close?

**Comment by mbarnach** [comment]
Thanks!
